# PYTHON 2.7.12 USAGE
try:
    let_us_cause_a_NameError
except NameError, err:
    print err, '--> our error message'
